name: Build Kivy APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v4

      - name: Build APK with Buildozer Action
        uses: Subreendude/Action-Android-Buildozer@v2
        with:
          command: buildozer -v android debug

      - name: Export Output Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: bin/*.apk
