name: Build Kivy APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK with Buildozer Action
        uses: Artemis-21/buildozer-action@v1
        with:
          # This automatically generates a fresh build config file on the server
          command: buildozer -v android debug
          repository_root: .

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: bin/*.apk
